// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1MYGP3l5T60F0PyjOYyEJX5D7vVTWsAg',
    appId: '1:209814928851:web:e4793c6b9ef0702e4b0326',
    messagingSenderId: '209814928851',
    projectId: 'jasarumahkuauth',
    authDomain: 'jasarumahkuauth.firebaseapp.com',
    databaseURL:
        'https://jasarumahkuauth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jasarumahkuauth.firebasestorage.app',
    measurementId: 'G-Q0LK2VBMT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzt5ME6omXzUPjosrFLcy7W2EjD4wY7DU',
    appId: '1:209814928851:android:b27d0e989b517af54b0326',
    messagingSenderId: '209814928851',
    projectId: 'jasarumahkuauth',
    databaseURL:
        'https://jasarumahkuauth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jasarumahkuauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9gppHD21FZ10vPCqnyzSSQdAbY9dUpaA',
    appId: '1:209814928851:ios:ec9a4f8e4b3a611a4b0326',
    messagingSenderId: '209814928851',
    projectId: 'jasarumahkuauth',
    databaseURL:
        'https://jasarumahkuauth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jasarumahkuauth.firebasestorage.app',
    androidClientId:
        '209814928851-lfl7mllmld985odb1haerkat365bskf0.apps.googleusercontent.com',
    iosClientId:
        '209814928851-2thuiskj58rg02sttdr88de626d912jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.jasarumahku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9gppHD21FZ10vPCqnyzSSQdAbY9dUpaA',
    appId: '1:209814928851:ios:d9c2a19121e036d34b0326',
    messagingSenderId: '209814928851',
    projectId: 'jasarumahkuauth',
    databaseURL:
        'https://jasarumahkuauth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jasarumahkuauth.firebasestorage.app',
    androidClientId:
        '209814928851-lfl7mllmld985odb1haerkat365bskf0.apps.googleusercontent.com',
    iosClientId:
        '209814928851-trbhkqqsk1lrhqkh5ld85oome16mubat.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzo9HjGNIPcnIysuIApRQ4CNIJyOknh0g',
    appId: '1:209814928851:web:dc4feec9cc23e1584b0326',
    messagingSenderId: '209814928851',
    projectId: 'jasarumahkuauth',
    authDomain: 'jasarumahkuauth.firebaseapp.com',
    databaseURL:
        'https://jasarumahkuauth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jasarumahkuauth.firebasestorage.app',
    measurementId: 'G-T173ZMT6MX',
  );
}
